"""Execution status
Revision ID: 27b95e8dad49
Revises: fbdb705a205e
Create Date: 2025-09-20 16:39:34.628280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '27b95e8dad49'
down_revision: Union[str, Sequence[str], None] = 'fbdb705a205e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    execution_status_enum = sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='executionstatus', create_type=False)
    execution_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('execution', 'status',
               existing_type=sa.BOOLEAN(),
               type_=execution_status_enum,
               existing_nullable=False,
               postgresql_using="CASE WHEN status THEN 'COMPLETED'::executionstatus ELSE 'RUNNING'::executionstatus END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='executionstatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               postgresql_using="CASE WHEN status = 'COMPLETED' THEN TRUE ELSE FALSE END")
    execution_status_enum = sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='executionstatus', create_type=False)
    execution_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
