"""Execution paused_id for node added
Revision ID: a4c98f636def
Revises: 27b95e8dad49
Create Date: 2025-09-21 11:06:07.475724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a4c98f636def'
down_revision: Union[str, Sequence[str], None] = '27b95e8dad49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('paused_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'paused_node_id')
    # ### end Alembic commands ###
