import httpx
from fastapi import APIRouter, HTTPException

from exports.prisma.client import prisma
from exports.redis.redis import redis_client
from worker.ai.services.e2b_validator import push_to_github

router = APIRouter()


@router.get("/repos")
async def get_user_repos(user_id: int):
    user = await prisma.user.find_unique(where={"id": user_id})
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    async with httpx.AsyncClient() as client:
        response = await client.get(
            "https://api.github.com/user/repos",
            headers={"Authorization": f"Bearer {user.githubAccessToken}"},
        )
        repos = response.json()

    return [{"name": repo["name"], "url": repo["html_url"]} for repo in repos]


@router.post("/push-code")
async def push_code_to_github(
    user_id: int, file_key: str, repo_name: str, create_new: bool = True
):
    user = await prisma.user.find_unique(where={"id": user_id})
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    sandbox_id = redis_client.get(f"sandbox:{file_key}")
    if not sandbox_id:
        raise HTTPException(status_code=404, detail="Sandbox has expired or not found")
    sandbox_id = (
        sandbox_id.decode("utf-8") if isinstance(sandbox_id, bytes) else sandbox_id
    )
    if create_new:
        async with httpx.AsyncClient() as client:
            repo_response = await client.post(
                "https://api.github.com/user/repos",
                headers={
                    "Authorization": f"Bearer {user.githubAccessToken}",
                    "Accept": "application/vnd.github+json",
                },
                json={
                    "name": repo_name,
                    "private": True,
                    "description": "Generated by Vision2React",
                },
            )
            if repo_response.status_code not in [200, 201]:
                raise HTTPException(
                    status_code=400,
                    detail=f"Failed to create repo: {repo_response.text}",
                )
    try:
        await push_to_github(
            sandbox_id=sandbox_id,
            github_token=user.githubAccessToken,
            github_username=user.githubUsername,
            repo_name=repo_name,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Git push failed: {str(e)}")
    return {
        "success": True,
        "repo_url": f"https://github.com/{user.githubUsername}/{repo_name}",
    }
