import asyncio
from typing import Dict, List

from e2b import AsyncSandbox

from config.settings import settings


async def create_nextjs_preview(components: List[Dict], main_page_code: str):
    sandbox = await AsyncSandbox.create(settings.e2b_template_id, timeout=3600)
    try:
        await sandbox.files.make_dir("/home/user/app/components")
        for comp in components:
            path = f"/home/user/app/components/{comp['component_name']}.tsx"
            await sandbox.files.write(path, comp["code"])

        await sandbox.files.write("/home/user/app/app/page.tsx", main_page_code)

        # Writing next.config.ts for remote images
        next_config = """import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'pub-c80d1e333d3f4fb9b278062947b49bb4.r2.dev',
        port: '',
        pathname: '/**',
      },
    ],
  },
};

export default nextConfig;
"""
        await sandbox.files.write("/home/user/app/next.config.ts", next_config)

        process = await sandbox.commands.run(
            "npm run dev -- -H 0.0.0.0 -p 3000", background=True, cwd="/home/user/app"
        )

        print("Waiting for Next.js dev server to start...")
        await asyncio.sleep(15)
        url = f"https://{sandbox.get_host(3000)}"
        return {"preview_url": url, "sandbox_id": sandbox.sandbox_id}
    except Exception as e:
        await sandbox.kill()
        raise e


async def push_to_github(
    sandbox_id: str, github_token: str, github_username: str, repo_name: str
):
    sandbox = await AsyncSandbox.connect(sandbox_id)
    try:
        await sandbox.commands.run(
            'git config --global user.email "default@vision2react.com"',
            cwd="/home/user/app",
        )
        await sandbox.commands.run(
            f'git config --global user.name "{github_username}"', cwd="/home/user/app"
        )
        await sandbox.commands.run("git init", cwd="/home/user/app")
        remote_url = (
            f"https://{github_token}@github.com/{github_username}/{repo_name}.git"
        )
        await sandbox.commands.run(
            f'git remote add origin "{remote_url}"', cwd="/home/user/app"
        )
        await sandbox.commands.run("git add .", cwd="/home/user/app")
        commit_message = "Generated By Vision2React"
        await sandbox.commands.run(
            f'git commit -m "{commit_message}"', cwd="/home/user/app"
        )
        await sandbox.commands.run("git branch -M main", cwd="/home/user/app")
        await sandbox.commands.run("git push -u origin main", cwd="/home/user/app")
        print(f"Successfully pushed to {github_username}/{repo_name}")
        return True
    except Exception as e:
        print(f"Git push failed: {str(e)}")
        raise e
    finally:
        await sandbox.kill()
